sudo: required
dist: trusty
language:
    - cpp
compiler:
    - gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - liblua5.1-dev

before_script:
    - chmod +x scripts/*
    - ./scripts/update-sol.sh
    - ./scripts/travis-before_script.sh
    
script:
    - ./scripts/travis-script.sh

