sudo: required
dist: trusty
language:
    - cpp
compiler:
    - gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7

before_script:
    - chmod +x scripts/*
    - ./scripts/travis-before_script.sh
    
script:
    - ./scripts/travis-script.sh

